nome=input('Qual é o seu nome? ')
maiu=nome.upper()
minu=nome.lower()
prim=(nome.split()[0])
pri=len(prim)
sem = nome.replace(' ', '')
nume = len(sem)
print(f'Seu nome em maiúsculo é {maiu}')
print(f'Seu nome em minusculo é {minu}')
print(f'Seu nome tem {nume} letras')
print(f'Seu primeiro nome tem {pri} letras')
